services:
  yoloCounter:
    build:
      context: .
      dockerfile: Dockerfile
#    image: ros_cuda_image:latest
    image: cuda:12.3.2-cudnn9-devel-ubuntu20.04
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - DISPLAY=$DISPLAY
      - ROS_MASTER_URI=http://localhost:11311
      - QT_X11_NO_MITSHM=1
    ports:
      - "11312:11312"
      - "8889:8889"
    working_dir: /root/deepLearning
    volumes:
      # - ../dataset:/root/datasets
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - /etc/sudoers.d:/etc/sudoers.d:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../:/root/deepLearning
      - ~/.ssh:/root/.ssh
      - ~/.config/nvim:/root/.config/nvim
    tty: true
    stdin_open: true
    privileged: true
